---
name: Tests for hyperscript

on:
  pull_request:
    paths:
      - ".github/workflows/go-test.yml"
      - "go.mod"
      - "**/*.go"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # test environment
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: '1.21.5'

      # running test
      - run: go test -v ./...
