---
name: Tests for hyperscript

on:
  pull_request:
    paths:
      - ".github/workflows/go-test.yml"
      - "go.mod"
      - "**/*.go"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      # test environment
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.21.5'

      # running test
      - run: go test -v ./...
